admin_membre:
    pattern:  /administration/membre
    defaults: { _controller: SiccUserBundle:Membre:index }

admin_membre_create:
    pattern:  /administration/membre/create
    defaults: { _controller: SiccUserBundle:Membre:index }