parameters:
#    sicc_user.example.class: Sicc\Bundle\UserBundle\Example

services:
#    sicc_user.example:
#        class: %sicc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
