<?php

namespace Sicc\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiaporamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaporamaRepository extends EntityRepository
{
}
