sicc_front_homepage:
    pattern:  /accueil
    defaults: { _controller: SiccFrontBundle:Default:index }
sicc_front_realisation:
    pattern:  /realisation
    defaults: { _controller: SiccFrontBundle:Realisation:index }
sicc_front_realisation_detail:
    pattern:  /realisation/{path}
    defaults: { _controller: SiccFrontBundle:Realisation:detail }
sicc_front_article:
    pattern:  /article/
    defaults: { _controller: SiccFrontBundle:Article:index }
sicc_front_article_focus:
    pattern:  /article/{path}
    defaults: { _controller: SiccFrontBundle:Article:focus }
sicc_front_contact:
    pattern:  /contact/
    defaults: { _controller: SiccFrontBundle:Email:new }
sicc_front_contact_envoi:
    pattern:  /contact/envoi
    defaults: { _controller: SiccFrontBundle:Email:create }

