parameters:
#    sicc_front.example.class: Sicc\Bundle\FrontBundle\Example

services:
#    sicc_front.example:
#        class: %sicc_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#     sicc.twig.sicc_extension:
#         class: Sicc\Bundle\FrontBundle\Twig\SiccExtension
#         tags:
#             - { name: twig.extension }