sicc_contact:
    resource: "@SiccContactBundle/Resources/config/routing.yml"
    prefix:   /

sicc_front:
    resource: "@SiccFrontBundle/Resources/config/routing.yml"
    prefix:   /

sicc_admin:
    resource: "@SiccAdminBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: SiccUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

administration_accueil:
    pattern:  /administration

