parameters:
#    sicc_admin.example.class: Sicc\Bundle\AdminBundle\Example

services:
#    sicc_admin.example:
#        class: %sicc_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
