<?php

namespace Sicc\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findOneByCounted()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(a) FROM SiccAdminBundle:Article a')
            ->getSingleScalarResult();
    }

    public function findByIdDesc(){
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM SiccAdminBundle:Article a ORDER BY a.id DESC')
            ->getResult();
    }

}
