<?php

namespace Sicc\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierRepository extends EntityRepository
{
    public function findOneByCounted()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(a) FROM SiccAdminBundle:Fichier a')
            ->getSingleScalarResult();
    }
}
