<?php

namespace Sicc\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeMembreRepository extends EntityRepository
{
}
